name: MultiversePlugin
version: 1.0.0
main: org.gabooj.PluginManager
description: A plugin used to manage worlds across a MC server.
author: gaboojie
api-version: '1.21'
commands:
  world:
    description: Manage worlds
    usage: /world <create|list|details|status|policy|world_name>
  group:
    description: Manage world groups
    usage: /group <create|add|remove|delete|list>
  warp:
    description: Manage warp locations per world group
    usage: /warp <warp name|list|create|delete>
  chat:
    description: Manage chat settings
    usage: /chat <color|format|nick|prefix|suffix>
  afk:
    description: Manage afk status
    usage: /afk
  tpa:
    description: Request teleportation to another player
    usage: /tpa <player|accept|deny> [name]
  claim:
    description: Claim chunks to prevent griefing
    usage: /claim <on/off/info>
  home:
    description: Go to your home in a given world
    usage: /home
